#!/usr/bin/env bash

set -euo pipefail

testdata=./tests/autotune_network.tests/
TMPDIR=/tmp/autotune_network/
mkdir -p $TMPDIR

run_test() {
	local name="${1##*/}"
	local rc=0
	echo -n "# $name "
	DATADIR="$1" ./utils/autotune_network.py > $TMPDIR/output
	cmp -s $1/expected_output $TMPDIR/output || rc=$?
	if [ "$rc" = '0' ]; then
		echo OK
	else
		diff -U 0 $testdata/$name/expected output
		echo FAIL
	fi
	return "$rc"
}


retval=0
# shellcheck disable=SC2044
for test in $(find $testdata -mindepth 1 -maxdepth 1 -type d); do
	if [ -f $test/expected_output ]; then
		run_test $test || retval=1
	fi
done
rm -rf $TMPDIR
exit $retval
