#!/usr/bin/env bash

set -euo pipefail

testdata=./tests/server-info-show.tests/
TMPDIR=/tmp/server-info-show/
mkdir -p $TMPDIR

run_test() {
	local name="${1##*/}"
	local rc=0
	echo -n "# $name "
	server-info --rate --directory="$1" &>"$TMPDIR/output" || rc=$?
	if [ "$rc" = '0' ]; then
		echo OK
	else
		cat "$TMPDIR/output"
		echo FAIL
	fi
	return "$rc"
}


retval=0
# shellcheck disable=SC2044
for test in $(find "$testdata" -mindepth 1 -maxdepth 1 -type d); do
	if [ -f "$test/expected_output" ]; then
		if ! run_test "$test"; then
			retval=1
			break
		fi
	fi
done
rm -rf $TMPDIR
exit "$retval"
