#!/usr/bin/env bash

set -euo pipefail

testdata=./tests/server-info-show.tests/
TMPDIR=/tmp/server-info-show/
mkdir -p $TMPDIR

run_test() {
	local name="${1##*/}"
	local rc=0
	echo -n "# $name "
	server-info --show --directory="$1" > $TMPDIR/output
	if [ "${REWRITE:-0}" = '1' ]; then
		server-info --show --directory="$1" > "$testdata/$name/expected_output.yml"
	fi
	cmp -s $1/expected_output.yml $TMPDIR/output || rc=$?
	if [ "$rc" = '0' ]; then
		echo OK
	else
		diff -U 5 "$testdata/$name/expected_output" "$TMPDIR/output"
		echo FAIL
	fi
	return "$rc"
}


retval=0
# shellcheck disable=SC2044
for test in $(find "$testdata" -mindepth 1 -maxdepth 1 -type d); do
	[ -f "$test/expected_output.yml" ] || continue
	run_test "$test" && continue
	[ "${REWRITE:-0}" = '1' ] && continue
	retval=1
	break
done
rm -rf $TMPDIR
exit "$retval"
