#!/bin/bash

# i40e driver sometimes bugs with RSS.
# interrupt counters freezes and all packet processing is doing by CPU0
# enabling and disabling RPS enables RSS, IDK why
# enabling both RPS and RSS is bad idea, so we disable it later
# don't use this script periodically, it can cause packet drops.
# only required for system startup.


hex_all_cpus() {
	python -c "print hex(int('1' * $(nproc), 2))" | sed 's/^0x//g'
}

i40e_tune() {
	local dev="$1"
	local all_cpus_mask
	all_cpus_mask="$(hex_all_cpus)"
	for rps_cpus in /sys/class/net/$dev/queues/*/rps_cpus; do
		echo "$all_cpus_mask" > $rps_cpus
	done
	rss-ladder "$dev"
	for rps_cpus in /sys/class/net/$dev/queues/*/rps_cpus; do
		echo 0 > $rps_cpus
	done
}

i40e_tune "$@"
