#!/usr/bin/env python

import os
import re
import optparse
from netutils_linux.link_rate import LinkRateTop


def device_list():
    parser = optparse.OptionParser()
    parser.add_option('-r', '--regex', dest='regex', help="filter net devices by regex-mask")
    parser.add_option('-d', '--devices', dest='devices', help="comma-separated devices list")
    options, args = parser.parse_args()
    if not all((options.regex, options.devices)):
        raise ValueError("please define --regex or --devices")
    if all((options.regex, options.devices)):
        raise ValueError("please, define only --regex or only --devices")
    if options.devices:
        devices = options.devices.split(',')
    elif options.regex:
        devices = [dev for dev in os.listdir('/sys/class/net/') if re.match(options.regex, dev)]
    else:
        devices = args[1:]
    if not devices:
        raise ValueError("No devices specified")
    return devices


if __name__ == "__main__":
    LinkRateTop(device_list()).run()
