#!/usr/bin/env python

from netutils_linux_monitoring.link_rate import LinkRateTop


if __name__ == "__main__":
    top = LinkRateTop()
    top.options = top.make_parser().parse_args()
    top.post_optparse()
    top.run()
