#!/bin/bash

set -eu

TMPDIR=/tmp/missed-pkts-monitor

mkdir -p $TMPDIR

while true; do
	date=$(date +%s)
	for i in "$@"; do
		echo -n "$i "
		ethtool -S $i | grep missed | awk '{print $2}'
	done > $TMPDIR/$date
	prev=$(ls $TMPDIR | tail -n 2 | head -n 1)
	last=$(ls $TMPDIR | tail -n 1)
	prev_md5="$(md5sum < $prev | awk '{print $1}')"
	last_md5="$(md5sum < $last | awk '{print $1}')"
	[ "$prev_md5" == "$last_md5" ] && rm -f $last

	if [ "$1" = 'oneshot' ]; then
		exit
	fi

	sleep 1
done
