#!/usr/bin/env python
# coding=utf-8

"""
Finds and sets compromise-value between avoiding
dropped/missing pkts and keeping a latency low.
"""

from netutils_linux_tuning.rx_buffers import RxBuffersTune

if __name__ == '__main__':
    RxBuffersTune()
