#!/usr/bin/env python
# coding: utf-8
# pylint: disable=C0111, C0103

import os
from netutils_linux_hardware.reader import Reader
from netutils_linux_hardware.assessor import Assessor


def main():
    # assess data in current directory
    if os.path.isfile(os.path.join(os.getcwd(), 'lspci')):
        datadir = os.getcwd()
    # assess data in DATADIR directory
    elif os.getenv('DATADIR'):
        datadir = os.getenv('DATADIR')
    # default debugging routine
    else:
        datadir = 'tests/autotune_network.tests/2xE5-2640.i350_and_82599ES.l2_mixed.masterconf'
        # datadir = 'tests/autotune_network.tests/kvm.l3.masterconf'
    data = Reader(datadir).info
    print Assessor(data)

if __name__ == '__main__':
    main()
