#!/usr/bin/env python
# coding: utf-8
# pylint: disable=C0111, C0103

import os

from six import print_

from netutils_linux_hardware.assessor import Assessor
from netutils_linux_hardware.reader import Reader


def main():
    cwd = os.getcwd()
    directory = cwd if os.path.isfile(os.path.join(cwd, 'lspci')) else os.getenv('DATADIR')
    reader = Reader(directory)
    assessor = Assessor(reader.info)
    print_(assessor)


if __name__ == '__main__':
    main()
