#!/usr/bin/env python
# coding: utf-8
# pylint: disable=C0111, C0103

import os
from six import print_
from netutils_linux_hardware.reader import Reader


def main():
    datadir = os.getenv('DATADIR')
    if os.path.isfile(os.path.join(os.getcwd(), 'lspci')):
        datadir = os.getcwd()
    print_(Reader(datadir))


if __name__ == '__main__':
    main()
