#!/usr/bin/env python
# coding: utf-8
# pylint: disable=C0111, C0103

import os

from six import print_

from netutils_linux_hardware.assessor import Assessor
from netutils_linux_hardware.reader import Reader

def get_datadir():
    default_data_directory = 'tests/autotune_network.tests/2xE5-2640.i350_and_82599ES.l2_mixed.masterconf'
    if os.path.isfile(os.path.join(os.getcwd(), 'lspci')):
        return os.getcwd()
    return os.environ.get('DATADIR', default_data_directory)
    

if __name__ == '__main__':
    print_(Assessor(Reader(get_datadir()).info))
