#!/usr/bin/env python

from netutils_linux_monitoring.softnet_stat import SoftnetStatTop


if __name__ == '__main__':
    top = SoftnetStatTop()
    top.options = top.make_parser().parse_args()
    top.post_optparse()
    top.run()
