#!/usr/bin/env python

import optparse

from ipaddress import ip_network
from six import print_


def main():
    parser = optparse.OptionParser()
    options, args = parser.parse_args()
    for arg in args:
        for ip in ip_network(unicode(arg, 'utf-8')):
            print_(ip)


if __name__ == '__main__':
    main()
